<a href="https://colab.research.google.com/github/gowtham-dd/Data-Science-Basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## Basics

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[1,2,34,5,6],[8,9,0,7,5]])
print (b)

[[ 1  2 34  5  6]
 [ 8  9  0  7  5]]


In [6]:
#Get Dimension
a.ndim
b.ndim

2

In [8]:
# Get Shape
a.shape
b.shape

(2, 5)

In [10]:
#  Get Type
b.dtype

dtype('int64')

In [11]:
# Get Size
b.itemsize

8

In [13]:
# total size
a.nbytes

24

## Access Specific row and col

In [17]:
a=np.array([[1,2,3,4,5,6,7],[8,9,0,1,2,31,23]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9,  0,  1,  2, 31, 23]])

In [19]:
# get specif element [r,c]
print(a[1,5])

31


In [21]:
a[0,:] # row


array([1, 2, 3, 4, 5, 6, 7])

In [24]:
a[:,2]

array([3, 0])

In [29]:
print(a[0,1:-1:2]) # row,start end step

[2 4 6]


In [31]:
a[1,5]=20
print(a)
a[1,5]=5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9  0  1  2 20 23]]
[[ 1  2  3  4  5  6  7]
 [ 8  9  0  1  2  5 23]]


## 3D

In [32]:
b=np.array([[[1,2],[3,4],[5,6]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]]]


In [34]:
b[0,0,1]# 0th row 0th col 1st element

np.int64(2)

In [38]:
# replace
b[0,0,1]=4
print(b)
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 4]
  [3 4]
  [5 6]]]


ValueError: could not broadcast input array from shape (2,2) into shape (1,2)

## Initialize Types of Arrays

In [41]:
# All 0 matrix
print(np.zeros((2,2)))
print(np.zeros((3,3,3)))

[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [42]:
# All 1 matrix
print(np.ones((2,2)))
print(np.ones((3,3,3)))

[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [43]:
#any num
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

## Random

In [46]:
np.random.rand(4,2,4)

array([[[0.63186009, 0.15564432, 0.52678043, 0.39111048],
        [0.42432251, 0.62742814, 0.37573035, 0.70380446]],

       [[0.93133836, 0.452758  , 0.46083222, 0.9983208 ],
        [0.47989108, 0.16928812, 0.98014589, 0.07451041]],

       [[0.70517672, 0.83552846, 0.807181  , 0.05232066],
        [0.7296049 , 0.06222407, 0.25554526, 0.63404911]],

       [[0.97624262, 0.32254697, 0.42320901, 0.40646473],
        [0.28677855, 0.47724886, 0.88773531, 0.47945022]]])

In [49]:
np.random.random_sample(4)

array([0.84343392, 0.43524529, 0.18482119, 0.43320215])

In [55]:
np.random.randint(4,6,size=(3,3))

array([[4, 5, 4],
       [4, 4, 5],
       [5, 5, 4]])

In [56]:
#identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
arr=np.array([1,2,3])
rl=np.repeat(arr,3,axis=0)
print(rl)

[1 1 1 2 2 2 3 3 3]


In [60]:
out= np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
out[1:4,1:4]=9
print(out)

[[1. 1. 1. 1. 1.]
 [1. 9. 9. 9. 1.]
 [1. 9. 9. 9. 1.]
 [1. 9. 9. 9. 1.]
 [1. 1. 1. 1. 1.]]


## Copy Arrys

In [61]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a) ## A is changed instead of b
# use .copy() to overcome

[100   2   3]


In [62]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


## Mathematics

In [63]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[2 4 6]
[0 0 0]
[1 4 9]
[1. 1. 1.]


## Linear Algebra

In [68]:
a=np.full((2,3),2)
a
b=np.full((3,2),1)
b

print(np.matmul(a,b))

[[6 6]
 [6 6]]


In [69]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics

In [72]:
a=np.array([[1,2,3],[4,5,6]])
np.min(a,axis=0)

array([1, 2, 3])

In [ ]:
## Load data
np.genfromtxt('abe.txt',delimiter=',')



## Boolean masking

In [75]:
a[a>5]

array([6])

In [79]:
a[1,2]

np.int64(6)